# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tsundere-Eddy Blog
description: In diesem Blog behandle ich alle Themen die mir so durch den Kopf gehen, egal ob Schimpftiraden, Programmier Fails, Spiele oder süße Anime Mädchen. Rechtschreib- und Grammatikfehler inklusive.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.eddydev.de/" # the base hostname & protocol for your site
github_username:  Der-Eddy

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
